respostas_estados = {'Acre':[['Acre'],[['Rio Branco']],['Norte']],
                     'Alagoas':[['Alagoas'],[['Maceió']],['Nordeste']],
                     'Amapá':[['Amapá'],[['Macapá']],['Norte']],
                     'Amazonas':[['Amazonas'],[['Manaus']],['Norte']],
                     'Bahia':[['Bahia'],[['Salvador']],['Nordeste']],
                     'Ceará':[['Ceará'],[['Fortaleza']],['Nordeste']],
                     'Espírito Santo':[['Espírito Santo'],[['Vitória']],['Sudeste']],
                     'Goiás':[['Goiás'],[['Goiânia']],['Centro-Oeste','Centro Oeste']],
                     'Maranhão':[['Maranhão'],[['São Luís']],['Nordeste']],
                     'Mato Grosso':[['Mato Grosso'],[['Cuiabá']],['Centro-Oeste','Centro Oeste']],
                     'Mato Grosso do Sul':[['Mato Grosso do Sul'],[['Campo Grande']],['Centro-Oeste','Centro Oeste']],
                     'Minas Gerais':[['Minas Gerais'],[['Belo Horizonte']],['Sudeste']],
                     'Pará':[['Pará'],[['Belém']],['Norte']],
                     'Paraíba':[['Paraíba'],[['João Pessoa']],['Nordeste']],
                     'Paraná':[['Paraná'],[['Curitiba']],['Sul']],
                     'Pernambuco':[['Pernambuco'],[['Recife']],['Nordeste']],
                     'Piauí':[['Piauí'],[['Teresina']],['Nordeste']],
                     'Rio de Janeiro':[['Rio de Janeiro'],[['Rio de Janeiro']],['Sudeste']],
                     'Rio Grande do Norte':[['Rio Grande do Norte'],[['Natal']],['Nordeste']],
                     'Rio Grande do Sul':[['Rio Grande do Sul'],[['Porto Alegre']],['Sul']],
                     'Rondônia':[['Rondônia'],[['Porto Velho']],['Norte']],
                     'Roraima':[['Roraima'],[['Boa Vista']],['Norte']],
                     'Santa Catarina':[['Santa Catarina'],[['Florianópolis']],['Sul']],
                     'São Paulo':[['São Paulo'],[['São Paulo']],['Sudeste']],
                     'Sergipe':[['Sergipe'],[['Aracaju']],['Nordeste']],
                     'Tocantins':[['Tocantins'],[['Palmas']],['Norte']],
                     'Distrito Federal':[['Distrito Federal'],[['Brasília']],['Centro-Oeste','Centro Oeste']]}

respostas_as = {'Brasil':[['Brasil'],[['Brasília']],['América do Sul']],
                'Argentina':[['Argentina'],[['Buenos Aires']],['América do Sul']],
                'Chile':[['Chile'],[['Santiago','Santiago de Chile']],['América do Sul']],
                'Peru':[['Peru'],[['Lima']],['América do Sul']],
                'Bolívia':[['Bolívia'],[['Sucre'],['La Paz']],['América do Sul']],
                'Paraguai':[['Paraguai'],[['Assunção','Asunción']],['América do Sul']],
                'Uruguai':[['Uruguai'],[['Montevidéu','Montevideu','Montevideo']],['América do Sul']],
                'Equador':[['Equador'],[['Quito']],['América do Sul']],
                'Colômbia':[['Colômbia'],[['Bogotá']],['América do Sul']],
                'Venezuela':[['Venezuela'],[['Caracas']],['América do Sul']],
                'Guiana':[['Guiana'],[['Georgetown']],['América do Sul']],
                'Suriname':[['Suriname'],[['Paramaribo']],['América do Sul']],
                'Guiana Francesa':[['Guiana Francesa'],[['Caiena']],['América do Sul']]}

respostas_an = {'Estados Unidos da América':[['Estados Unidos','Estados Unidos da América'],[['Washington','Washington, DC','Washington,DC']],['América do Norte']],
                'Canadá':[['Canadá'],[['Ottawa','Otava']],['América do Norte']],
                'México':[['México'],[['Cidade do México','Ciudad de México']],['América do Norte']],
                'Groelândia':[['Groelândia','Groenlândia','Gronelândia'],[['Nuuk','Nuque','Godthåb']],['América do Norte']]}

respostas_ac = {'Panamá':[['Panamá'],[['Cidade do Panamá','Ciudad de Panamá']],['América Central']],
                'Costa Rica':[['Costa Rica'],[['São José','San José']],['América Central']],
                'Nicarágua':[['Nicarágua','Nicaragua'],[['Manágua','Managua']],['América Central']],
                'Honduras':[['Honduras'],[['Tegucigalpa']],['América Central']],
                'Guatemala':[['Guatemala'],[['Cidade da Guatemala','Ciudad de Guatemala']],['América Central']],
                'El Salvador':[['Salvador','El Salvador'],[['São Salvador','San Salvador']],['América Central']],
                'Belize':[['Belize'],[['Belmopã','Belmopan']],['América Central']],
                'Cuba':[['Cuba'],[['Havana','La Habana']],['América Central']],
                'Jamaica':[['Jamaica'],[['Kingston']],['América Central']],
                'Bahamas':[['Bahamas','Baamas'],[['Nassau']],['América Central']],
                'Haiti':[['Haiti'],[['Porto Príncipe','Port-au-Prince','Pòtoprens','Porto do Príncipe']],['América Central']],
                'Dominica':[['Domínica','Dominica'],[['Roseau']],['América Central']],
                'São Cristóvão e Neves':[['São Cristóvão e Neves','São Cristóvão e Névis','Névis'],[['Basseterre']],['América Central']],
                'Antígua e Barbuda':[['Antígua e Barbuda'],[['São João',"Saint John's"]],['América Central']],
                'República Dominicana':[['República Dominicana'],[['São Domingos','Santo Domingo']],['América Central']],
                'Trindade e Tobago':[['Trindade e Tobago','Trinidade e Tobago','Trinidad e Tobago '],[['Porto de Espanha','Port of Spain','Porto da Espanha']],['América Central']],
                'Barbados':[['Barbados'],[['Bridgetown']],['América Central']],
                'Granada':[['Granada','Grenada'],[['São Jorge',"Saint George's"]],['América Central']],
                'Santa Lúcia':[['Santa Lúcia'],[['Castries']],['América Central']],
                'São Vicente e Granadinas':[['São Vicente e Granadinas'],[['Kingstown']],['América Central']],
                'Aruba':[['Aruba'],[['Oranjestad']],['América Central']],
                'Curaçau':[['Curaçau'],[['Willemstad']],['América Central']],
                'São Martinho':[['São Martinho'],[['Philipsburg']],['América Central']]}

respostas_af = {'África do Sul':[['África do Sul'],[['Pretória'],['Cidade do Cabo'],['Bloemfontein']],['África']],
                'Lesoto':[['Lesoto', 'Lessoto'],[['Maseru']],['África']],
                'Essuatíni':[['Essuatíni'],[['Mebabane','Mbabane'],['Lobamba']],['África']],
                'Namíbia':[['Namíbia'],[['Vinduque','Windhoek']],['África']],
                'Botsuana':[['Botsuana','Botswana'],[['Gaborone']],['África']],
                'Moçambique':[['Moçambique'],[['Maputo']],['África']],
                'Angola':[['Angola'],[['Luanda']],['África']],
                'Madagáscar':[['Madagáscar','Madagascar'],[['Antananarivo']],['África']],
                'Zimbábue':[['Zimbábue','Zimbabué','Zimbabwe'],[['Harare']],['África']],
                'Zâmbia':[['Zâmbia'],[['Lusaca','Lusaka']],['África']],
                'Malawi':[['Malawi','Maláui','Malaui','Malavi','Malávi'],[['Lilongué','Lilôngue','Lilóngue','Lilongue','Lilongwe']],['África']],
                'Maurício':[['Maurícia','Maurício'],[['Porto Luís','Port-Louis','Port Louis']],['África']],
                'Comores':[['Comores'],[['Moroni']],['África']],
                'Burundi':[['Burundi','Burúndi'],[['Guitega','Gitega']],['África']],
                'Djibouti':[['Djibuti','Jibuti'],[['Djibuti','Jibuti']],['África']],
                'Eritreia':[['Eritreia'],[['Asmara','Asmera']],['África']],
                'Etiópia':[['Etiópia'],[['Adis Abeba']],['África']],
                'Quênia':[['Quênia','Quénia'],[['Nairóbi','Nairobi']],['África']],
                'Ruanda':[['Ruanda'],[['Quigali','Kigali']],['África']],
                'Seicheles':[['Seicheles','Seychelles'],[['Vitória','Victoria','Porto Vitória','Port Victoria','Mahé','Vitória das Seicheles']],['África']],
                'Somália':[['Somália'],[['Mogadíscio','Mogadixo','Muqdisho','Xamar','مقديشو','Maqadīshū']],['África']],
                'Tanzânia':[['Tanzânia','Tanzania'],[['Dodoma']],['África']],
                'Uganda':[['Uganda'],[['Campala']],['África']],
                'Chade':[['Chade','Tchade'],[['Jamena',"N'Djamena"]],['África']],
                'República do Congo':[['Congo','República do Congo','Congo-Brazavile','Congo-Brazzaville'],[['Brazzaville','Brazavile']],['África']],
                'República Centro-Africana':[['República Centro-Africana','República da África-Central','Centráfrica'],[['Bangui']],['África']],
                'República Democrática do Congo':[['República Democrática do Congo','RDC','RD Congo','Congo','Congo-Quinxassa','Congo-Kinshasa'],[['Quinxassa','Quinxasa','Kinshasa']],['África']],
                'Argélia':[['Argélia'],[['Argel']],['África']],
                'Egito':[['Egito'],[['Cairo']],['África','Ásia']],
                'Líbia':[['Líbia'],[['Trípoli']],['África']],
                'Marrocos':[['Marrocos'],[['Rabat','Rabate','Rebate']],['África']],
                'Sudão':[['Sudão'],[['Cartum']],['África']],
                'Sudão do Sul':[['Sudão do Sul','Sudão Meridional'],[['Juba']],['África']],
                'Tunísia':[['Tunísia'],[['Tunes','Túnis']],['África']],
                'Benim':[['Benim'],[['Porto Novo'],['Cotonu']],['África']],
                'Burquina Fasso':[['Burquina Fasso','Burquina Faso','Burquina'],[['Uagadugu','Ouagadougou']],['África']],
                'Cabo Verde':[['Cabo Verde'],[['Praia']],['África']],
                'Camarões':[['Camarões'],[['Iaundé','Iaundê']],['África']],
                'Costa do Marfim':[['Costa do Marfim'],[['Iamussucro','Yamoussoukro'],['Abidjã','Abijão','Abijã']],['África']],
                'Gabão':[['Gabão'],[['Libreville','Librevile']],['África']],
                'Gâmbia':[['Gâmbia'],[['Banjul']],['África']],
                'Gana':[['Gana'],[['Acra','Accra']],['África']],
                'Guiné':[['Guiné'],[['Conacri','Conakry']],['África']],
                'Guiné-Bissau':[['Guiné-Bissau'],[['Bissau']],['África']],
                'Guiné Equatorial':[['Guiné Equatorial'],[['Malabo'],['Cidade da Paz','Ciudad de la Paz','Ville de Paix']],['África']],
                'Libéria':[['Libéria'],[['Monróvia','Monrovia']],['África']],
                'Mali':[['Mali','Máli'],[['Bamaco','Bamako']],['África']],
                'Mauritânia':[['Mauritânia'],[['Nuaquexote','Nuaquechote','Nouakchott']],['África']],
                'Níger':[['Níger'],[['Niamei','Niamey']],['África']],
                'Nigéria':[['Nigéria'],[['Abuja']],['África']],
                'São Tomé e Príncipe':[['São Tomé e Príncipe'],[['São Tomé']],['África']],
                'Serra Leoa':[['Serra Leoa'],[['Freetown']],['África']],
                'Togo':[['Togo'],[['Lomé']],['África']],
                'Senegal':[['Senegal'],[['Dacar','Dakar']],['África']],
                'Somalilândia':[['Somalilândia'],[['Hargeisa']],['África']],
                'República Árabe Saaraui Democrática':[['República Árabe Saaraui Democrática','República Saaraui'],[['El Aiune','Laiune'],['Tifariti']],['África']]}

respostas_eu = {'Albânia':[['Albânia'],[['Tirana','Tiranë','Tirona']],['Europa']],
                'Alemanha':[['Alemanha'],[['Berlim','Berlin']],['Europa']],
                'Andorra':[['Andorra'],[['Andorra-a-Velha','Andorra la Vella']],['Europa']],
                'Armênia':[['Armênia','Arménia'],[['Erevã','Erevan','Ierevan','Ierevã']],['Ásia','Europa']],
                'Áustria':[['Áustria'],[['Viena','Wien']],['Europa']],
                'Azerbaijão':[['Azerbaijão'],[['Bacu','Baku','Bakı']],['Ásia','Europa']],
                'Bélgica':[['Bélgica'],[['Bruxelas','Cidade de Bruxelas','Bruxelles-Ville','Ville de Bruxelles','Stad Brussel']],['Europa']],
                'Bielorrússia':[['Bielorrússia','Belarus'],[['Minsk']],['Europa']],
                'Bósnia e Herzegovina':[['Bósnia e Herzegovina','Bósnia-Herzegovina'],[['Saraievo','Sarajevo','Serajevo']],['Europa']],
                'Bulgária':[['Bulgária'],[['Sófia']],['Europa']],
                'Cazaquistão':[['Cazaquistão'],[['Astana']],['Ásia','Europa']],
                'Chipre':[['Chipre'],[['Nicósia']],['Ásia','Europa']],
                'Croácia':[['Croácia'],[['Zagrebe','Zagreb']],['Europa']],
                'Dinamarca':[['Dinamarca'],[['Copenhague','Copenhaga']],['Europa']],
                'Eslováquia':[['Eslováquia'],[['Bratislava']],['Europa']],
                'Eslovênia':[['Eslovênia','Eslovénia'],[['Liubliana','Ljubljana']],['Europa']],
                'Espanha':[['Espanha'],[['Madri','Madrid']],['Europa']],
                'Estônia':[['Estônia','Estónia'],[['Taline','Tallinn','Talim','Talin']],['Europa']],
                'Finlândia':[['Finlândia'],[['Helsinque','Helsínquia']],['Europa']],
                'França':[['França'],[['Paris']],['Europa']],
                'Geórgia':[['Geórgia'],[['Tiblíssi','Tbilísi']],['Europa','Ásia']],
                'Grécia':[['Grécia'],[['Atenas']],['Europa']],
                'Hungria':[['Hungria'],[['Budapeste','Budapest']],['Europa']],
                'Irlanda':[['Irlanda'],[['Dublim','Dublin']],['Europa']],
                'Islândia':[['Islândia'],[['Reiquiavique','Reykjavík']],['Europa']],
                'Itália':[['Itália'],[['Roma']],['Europa']],
                'Letônia':[['Letônia','Letónia'],[['Riga','Rīga']],['Europa']],
                'Liechtenstein':[['Liechtenstein'],[['Vaduz']],['Europa']],
                'Lituânia':[['Lituânia'],[['Vilna','Vilnius','Vílnius']],['Europa']],
                'Luxemburgo':[['Luxemburgo'],[['Luxemburgo']],['Europa']],
                'Macedônia do Norte':[['Macedônia do Norte','Macedónia do Norte'],[['Escópia','Skopje','Skopie']],['Europa']],
                'Malta':[['Malta'],[['Valeta','Valletta']],['Europa']],
                'Moldávia':[['Moldávia','Moldova'],[['Quixinau','Quichinau','Chisinau','Quixineve']],['Europa']],
                'Mônaco':[['Mônaco','Principado de Mônaco','Mónaco'],[['Mônaco','Monaco-Ville','Munegu-Vila']],['Europa']],
                'Montenegro':[['Montenegro'],[['Podgoriza','Podgoritza','Podgorica']],['Europa']],
                'Noruega':[['Noruega'],[['Oslo']],['Europa']],
                'Países Baixos':[['Países Baixos','Holanda'],[['Amesterdã','Amesterdão','Amsterdam'],['Haia']],['Europa']],
                'Polônia':[['Polônia','Polónia'],[['Varsóvia','Warszawa']],['Europa']],
                'Portugal':[['Portugal'],[['Lisboa']],['Europa']],
                'Reino Unido':[['Reino Unido'],[['Londres','London']],['Europa']],
                'Escócia':[['Escócia'],[['Edimburgo','Edinburgh']],['Europa']],
                'Inglaterra':[['Inglaterra'],[['Londres','London']],['Europa']],
                'Irlanda do Norte':[['Irlanda do Norte'],[['Belfaste','Belfast','Belfástia','Béal Feirste']],['Europa']],
                'Gales':[['Gales','País de Gales'],[['Cardife','Cardiff','Cardívio']],['Europa']],
                'Chéquia':[['Chéquia','Tchéquia'],[['Praga','Praha']],['Europa']],
                'Romênia':[['Romênia'],[['Bucareste']],['Europa']],
                'Rússia':[['Rússia'],[['Moscou','Moscovo']],['Ásia','Europa']],
                'San Marino':[['São Marinho','San Marino','São Marino'],[['São Marinho','San Marino','São Marino']],['Europa']],
                'Sérvia':[['Sérvia'],[['Belgrado']],['Europa']],
                'Suécia':[['Suécia'],[['Estocolmo','Stockholm']],['Europa']],
                'Suíça':[['Suíça'],[['Berna']],['Europa']],
                'Turquia':[['Turquia'],[['Ancara','Ankara','Ancira','Angora']],['Ásia','Europa']],
                'Ucrânia':[['Ucrânia'],[['Kiev','Kyiv','Quieve']],['Europa']],
                'Vaticano':[['Vaticano','cidade do Vaticano'],[['Cidade do Vaticano']],['Europa']],
                'Abecásia':[['Abecásia'],[['Sucumi','Sukhumi']],['Europa','Ásia']],
                'Kosovo':[['Kosovo','Cossovo','Cosovo','Kossovo'],[['Pristina']],['Europa']],
                'Transnístria':[['Transnístria','Transdnístria','Transdniestre','Transdniéstria'],[['Tiráspol','Tiraspol']],['Europa']],
                'Ossétia do Sul':[['Ossétia do Sul'],[['Tsequinváli','Tsequinval','Cequinváli','Cequinval','Tskhinvali','Cchinvali','Cxinvali']],['Europa','Ásia']],
                'Chipre do Norte':[['Chipre do Norte'],[['Nicósia do Norte']],['Ásia','Europa']],
                'Artsaque':[['Artsaque'],[['Estepanaquerte','Canquendi','Stepanakert']],['Ásia','Europa']]}

respostas_aa = {'Afeganistão':[['Afeganistão'],[['Cabul','Cábul']],['Ásia']],
                'Arábia Saudita':[['Arábia Saudita'],[['Riade']],['Ásia']],
                'Armênia':[['Armênia','Arménia'],[['Erevã','Erevan','Ierevan','Ierevã']],['Ásia','Europa']],
                'Azerbaijão':[['Azerbaijão'],[['Bacu','Baku','Bakı']],['Ásia','Europa']],
                'Barém':[['Barém','Bahrein','Barein','Bareine'],[['Manama']],['Ásia']],
                'Bangladesh':[['Bangladesh','Bangladexe','Bangladeche'],[['Daca','Dhaka']],['Ásia']],
                'Brunei':[['Brunei'],[['Bandar Seri Begauã','Bandar Seri Begawan','Bandar Seri Begauane']],['Ásia']],
                'Butão':[['Butão'],[['Timbu','Thimphu','Timpu']],['Ásia']],
                'Camboja':[['Camboja','Cambodja'],[['Pnom Pene','Penome Pene','Phnom Penh','Pnom Pen']],['Ásia']],
                'Catar':[['Catar','Qatar'],[['Doha','Doa']],['Ásia']],
                'Cazaquistão':[['Cazaquistão'],[['Astana']],['Ásia','Europa']],
                'China':[['China'],[['Pequim']],['Ásia']],
                'Chipre':[['Chipre'],[['Nicósia']],['Ásia','Europa']],
                'Coreia do Norte':[['Coreia do Norte','República Popular Democrática da Coreia'],[['Pyongyang','Pionguiangue']],['Ásia']],
                'Coreia do Sul':[['Coreia do Sul','República Popular Democrática da Coreia'],[['Seul']],['Ásia']],
                'Egito':[['Egito'],[['Cairo']],['África','Ásia']],
                'Emirados Árabes Unidos':[['Emirados Árabes Unidos','Emirados Árabes'],[['Abu Dabi','Abu Dhabi']],['Ásia']],
                'Filipinas':[['Filipinas'],[['Manila']],['Ásia']],
                'Geórgia':[['Geórgia'],[['Tiblíssi','Tbilísi']],['Europa','Ásia']],
                'Iêmen':[['Iêmen','Iémen'],[['Saná','Sanaa','Sanaá']],['Ásia']],
                'Índia':[['Índia'],[['Nova Déli','Nova Deli','Nova Delhi','Nova Délhi','New Delhi']],['Ásia']],
                'Indonésia':[['Indonésia'],[['Jacarta']],['Ásia','Oceania']],
                'Irã':[['Irã','Irão'],[['Teerã','Teerão']],['Ásia']],
                'Iraque':[['Iraque'],[['Bagdá','Bagdade','Baguedade','Bagdad']],['Ásia']],
                'Israel':[['Israel','Palestina','Lixo'],[['Jerusalém']],['Ásia']],
                'Japão':[['Japão'],[['Tóquio']],['Ásia']],
                'Jordânia':[['Jordânia'],[['Amã']],['Ásia']],
                'Kuwait':[['Kuwait'],[['Kuwait','Koweit','Coveite','Couaite','Quaite','Cuaite']],['Ásia']],
                'Laos':[['Laos'],[['Vientiane','Vienciana']],['Ásia']],
                'Líbano':[['Líbano'],[['Beirute']],['Ásia']],
                'Malásia':[['Malásia'],[['Cuala Lumpur','Kuala','Quala','Cualalampur','Kuala Lumpur','Quala Lumpur'],['Putrajaia','Putrajaya']],['Ásia']],
                'Maldivas':[['Maldivas'],[['Malé']],['Ásia']],
                'Myanmar':[['Mianmar','Myanmar','Birmânia'],[['Nepiedó','Naypyidaw','Nay Pyi Taw']],['Ásia']],
                'Mongólia':[['Mongólia'],[['Ulã Bator','Ulan Bator']],['Ásia']],
                'Nepal':[['Nepal'],[['Catmandu']],['Ásia']],
                'Omã':[['Omã','Omão'],[['Mascate']],['Ásia']],
                'Palestina':[['Palestina'],[['Jerusalém'],['Gaza'],['Ramala','Ramallah','Ramalá']],['Ásia']],
                'Paquistão':[['Paquistão'],[['Islamabade','Islamabad']],['Ásia']],
                'Quirguistão':[['Quirguistão','Quirguizistão','Quirguízia'],[['Bisqueque','Pispeque','Frunze']],['Ásia']],
                'Rússia':[['Rússia'],[['Moscou','Moscovo']],['Ásia','Europa']],
                'Singapura':[['Singapura'],[['Singapura']],['Ásia']],
                'Síria':[['Síria'],[['Damasco']],['Ásia']],
                'Sri Lanka':[['Sri Lanka','Sri Lanca','Seri Lanca'],[['Seri Jaiavardenapura-Cota','Sri Jaiavardenapura-Cota','Sri Jayawardenapura-Kotte','Cota','Kotte']],['Ásia']],
                'Tajiquistão':[['Tajiquistão','Tadjiquistão'],[['Duxambé','Duchambé']],['Ásia']],
                'Tailândia':[['Tailândia'],[['Bancoque','Bangkok','Banguecoque']],['Ásia']],
                'Timor-Leste':[['Timor-Leste'],[['Díli']],['Ásia','Oceania']],
                'Turcomenistão':[['Turcomenistão','Turquemenistão'],[['Asgabade','Asgabate','Ascabade']],['Ásia']],
                'Turquia':[['Turquia'],[['Ancara','Ankara','Ancira','Angora']],['Ásia','Europa']],
                'Uzbequistão':[['Uzbequistão','Usbequistão'],[['Tasquente']],['Ásia']],
                'Vietnã':[['Vietnã','Vietname'],[['Hanói']],['Ásia']],
                'Abecásia':[['Abecásia'],[['Sucumi','Sukhumi']],['Europa','Ásia']],
                'Artsaque':[['Artsaque'],[['Estepanaquerte','Canquendi','Stepanakert']],['Ásia','Europa']],
                'Chipre do Norte':[['Chipre do Norte'],[['Nicósia do Norte']],['Ásia','Europa']],
                'Ossétia do Sul':[['Ossétia do Sul'],[['Tsequinváli','Tsequinval','Cequinváli','Cequinval','Tskhinvali','Cchinvali','Cxinvali']],['Europa','Ásia']]}

respostas_oc = {'Austrália':[['Austrália'],[['Camberra','Canberra']],['Oceania']],
                'Nova Zelândia':[['Nova Zelândia'],[['Wellington']],['Oceania']],
                'Timor-Leste':[['Timor-Leste'],[['Díli']],['Ásia','Oceania']],
                'Fiji':[['Fiji','Fíji','Fidji'],[['Suva']],['Oceania']],
                'Indonésia':[['Indonésia'],[['Jacarta']],['Ásia','Oceania']],
                'Papua-Nova Guiné':[['Papua-Nova Guiné','Papua Nova Guiné','Papuásia-Nova Guiné'],[['Porto Moresby','Port Moresby']],['Oceania']],
                'Ilhas Salomão':[['Ilhas Salomão'],[['Honiara']],['Oceania']],
                'Vanuatu':[['Vanuatu'],[['Porto Vila','Port Vila','Port-Vila']],['Oceania']],
                'Micronésia':[['Micronésia','Estados Federados da Micronésia'],[['Paliquir','Palikir']],['Oceania']],
                'Kiribati':[['Kiribati','Quiribáti','Quiribati'],[['Taraua do Sul','Tarawa do Sul']],['Oceania']],
                'Ilhas Marshall':[['Ilhas Marshall'],[['Majuro']],['Oceania']],
                'Nauru':[['Nauru'],[['Iarém','Yaren']],['Oceania']],
                'Palau':[['Palau'],[['Ngerulmud']],['Oceania']],
                'Ilhas Cook':[['Ilhas Cook'],[['Avarua']],['Oceania']],
                'Niue':[['Niue','Niuê'],[['Alofi']],['Oceania']],
                'Samoa':[['Samoa'],[['Apia']],['Oceania']],
                'Tonga':[['Tonga'],[['Nucualofa','Nukuʻalofa']],['Oceania']],
                'Tuvalu':[['Tuvalu'],[['Funafuti']],['Oceania']]}

respostas = respostas_estados | respostas_as | respostas_an | respostas_ac | respostas_af | respostas_eu | respostas_aa | respostas_oc

respostas_independentes = {'Ossétia do Sul':[['Ossétia do Sul'],[['Tsequinváli','Tsequinval','Cequinváli','Cequinval','Tskhinvali','Cchinvali','Cxinvali']],['Europa','Ásia']],
                           'Chipre do Norte':[['Chipre do Norte'],[['Nicósia do Norte']],['Ásia','Europa']],
                           'Abecásia':[['Abecásia'],[['Sucumi','Sukhumi']],['Europa','Ásia']],
                           'Israel':[['Israel','Palestina','Lixo'],[['Jerusalém']],['Ásia']],
                           'Coreia do Sul':[['Coreia do Sul','República Popular Democrática da Coreia'],[['Seul']],['Ásia']],
                           'Transnístria':[['Transnístria','Transdnístria','Transdniestre','Transdniéstria'],[['Tiráspol','Tiraspol']],['Europa']],
                           'Kosovo':[['Kosovo','Cossovo','Cosovo','Kossovo'],[['Pristina']],['Europa']],
                           'Somalilândia':[['Somalilândia'],[['Hargeisa']],['África']],
                           'República Árabe Saaraui Democrática':[['República Árabe Saaraui Democrática','República Saaraui'],[['El Aiune','Laiune'],['Tifariti']],['África']]}

respostas_fantasmas = {'Artsaque':[['Artsaque'],[['Estepanaquerte','Canquendi','Stepanakert']],['Ásia','Europa']]}
